### ISSUE TITLE
Create UMLObject, Relation, Controller Classes

### ISSUE THREAD

**Issue by AdamG-L** [mucsci-students/2024sp-420-CWorld#4]
Create UMLObject, Relation, Controller Classes
 
 - [ ] Create UMLObject, Relation, Controller Classes
 
 - Primary: @mention
 - Secondary: @mention
 - Size: (fib number)
 - Actual Size: (fib number after completion)
 - Actual Time: (in minutes or hours -- after completion)

**Comment by almostTaklu** [comment]
This is divided into individual tasks.
